import { TravelBuddy, BookingStatus } from "../types";

export const TRAVEL_DATA: TravelBuddy[] = [
  {
    id: "1",
    name: "John Doe",
    profileImg: "https://avatar.iran.liara.run/public",
    rating: 4.8,
    languages: ["English", "Spanish"],
    departureTime: "10:30",
    departureDate: "12 Mar 2024",
    departureLocation: "London (LHR)",
    arrivalTime: "14:30",
    arrivalDate: "12 Mar 2024",
    arrivalLocation: "Paris (CDG)",
    type: "upcoming",
  },
  {
    id: "2",
    name: "Jane Smith",
    profileImg: "https://avatar.iran.liara.run/public",
    rating: 4.9,
    languages: ["English", "French"],
    departureTime: "08:45",
    departureDate: "15 Mar 2024",
    departureLocation: "New York (JFK)",
    arrivalTime: "20:15",
    arrivalDate: "15 Mar 2024",
    arrivalLocation: "Tokyo (NRT)",
    type: "requests",
    requestInfo: {
      sentDate: "16 January, 2024",
      requestType: "travel",
      passengers: 2,
    },
  },
  {
    id: "3",
    name: "Mike Johnson",
    profileImg: "https://avatar.iran.liara.run/public",
    rating: 4.7,
    languages: ["English", "German"],
    departureTime: "16:20",
    departureDate: "10 Feb 2024",
    departureLocation: "Berlin (BER)",
    arrivalTime: "18:45",
    arrivalDate: "10 Feb 2024",
    arrivalLocation: "Amsterdam (AMS)",
    type: "requests",
    requestInfo: {
      sentDate: "15 January, 2024",
      requestType: "courier",
      documentType: "Legal Documents",
    },
  },
  {
    id: "4",
    name: "Sarah Wilson",
    profileImg: "https://avatar.iran.liara.run/public",
    rating: 5.0,
    languages: ["English", "Italian"],
    departureTime: "09:15",
    departureDate: "5 Feb 2024",
    departureLocation: "Rome (FCO)",
    arrivalTime: "11:30",
    arrivalDate: "5 Feb 2024",
    arrivalLocation: "Madrid (MAD)",
    type: "previous",
    ratingInfo: {
      rated: true,
      userRating: 5,
      comment: "Exceeded my expectations by all means",
    },
  },
  {
    id: "5",
    name: "David Brown",
    profileImg: "https://avatar.iran.liara.run/public",
    rating: 4.2,
    languages: ["English", "Portuguese"],
    departureTime: "14:20",
    departureDate: "1 Feb 2024",
    departureLocation: "Lisbon (LIS)",
    arrivalTime: "16:45",
    arrivalDate: "1 Feb 2024",
    arrivalLocation: "Barcelona (BCN)",
    type: "canceled",
    canceledDate: "11th February, 2024",
  },
];

export const emptyMessages: { [key in BookingStatus]: string } = {
  upcoming:
    "You currently have no upcoming bookings. If you have recently sent requests for a Travel Buddy or Buddy Courier, please wait for a buddy to accept your request or check them in the Requests tab.",
  previous: "Your completed bookings will be shown here.",
  requests:
    "You currently have no pending requests. Search for a Travel Buddy or Buddy Courier and send them a request today!",
  canceled: "You currently have no canceled bookings.",
};
